# Generated by Django 4.1.4 on 2023-03-08 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingExerciseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingParametersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField(blank=True, null=True)),
                ('reps', models.CharField(blank=True, max_length=10, null=True)),
                ('tempo', models.CharField(blank=True, max_length=10, null=True)),
                ('rir', models.CharField(blank=True, max_length=10, null=True)),
                ('rest', models.IntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.trainingexercisemodel')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.trainingmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.trainingmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='trainingmodel',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_training_name'),
        ),
        migrations.AddConstraint(
            model_name='trainingexercisemodel',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_exercise_of_training_name'),
        ),
        migrations.AddConstraint(
            model_name='planmodel',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_plan_name'),
        ),
    ]
