# Generated by Django 4.1.4 on 2023-03-11 17:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanModel',
            new_name='Plan',
        ),
        migrations.RenameModel(
            old_name='TrainingModel',
            new_name='Training',
        ),
        migrations.RenameModel(
            old_name='TrainingExerciseModel',
            new_name='TrainingExercise',
        ),
        migrations.RenameModel(
            old_name='TrainingParametersModel',
            new_name='TrainingParameters',
        ),
        migrations.RenameModel(
            old_name='TrainingResultModel',
            new_name='TrainingResult',
        ),
    ]
