# Generated by Django 4.1.4 on 2023-03-09 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routines', '0002_remove_planmodel_training_planmodel_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_nr', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('rir', models.IntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.trainingexercisemodel')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.trainingmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='trainingresultmodel',
            constraint=models.UniqueConstraint(fields=('user', 'training', 'exercise', 'serie_nr'), name='unique_serie'),
        ),
    ]
