# Generated by Django 4.1.4 on 2023-03-10 16:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_trainingresultmodel_trainingresultmodel_unique_serie'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trainingresultmodel',
            name='unique_serie',
        ),
        migrations.RemoveField(
            model_name='trainingresultmodel',
            name='exercise',
        ),
        migrations.AddField(
            model_name='trainingresultmodel',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='trainingresultmodel',
            name='serie_nr',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainingresultmodel',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.trainingparametersmodel'),
        ),
    ]
