# Generated by Django 4.1.4 on 2023-03-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0004_remove_trainingresultmodel_unique_serie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingresultmodel',
            name='reps',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainingresultmodel',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
