# Generated by Django 4.1.4 on 2023-03-10 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0005_alter_trainingresultmodel_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingresultmodel',
            name='reps',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='trainingresultmodel',
            name='rir',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='trainingresultmodel',
            name='serie_nr',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='trainingresultmodel',
            name='weight',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddConstraint(
            model_name='trainingresultmodel',
            constraint=models.UniqueConstraint(fields=('user', 'training', 'date', 'serie_nr'), name='unique_serie_for_todays_training'),
        ),
    ]
