# Generated by Django 4.1.4 on 2023-03-10 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0006_alter_trainingresultmodel_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingparametersmodel',
            name='rest',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='trainingparametersmodel',
            name='series',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
