# Generated by Django 4.1.4 on 2023-03-10 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0007_alter_trainingparametersmodel_rest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingparametersmodel',
            name='rest',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='trainingparametersmodel',
            name='rir',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='trainingparametersmodel',
            name='tempo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='trainingresultmodel',
            name='rir',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
