# Generated by Django 4.1.4 on 2023-03-10 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0008_alter_trainingparametersmodel_rest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingparametersmodel',
            name='rest',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
