# Generated by Django 4.1.4 on 2023-01-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="series",
            field=models.CharField(default="Serie nr: ", max_length=20),
        ),
    ]
