# Generated by Django 4.1.4 on 2023-01-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_training_series"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="series",
            field=models.CharField(default="Serie nr: ", max_length=15),
        ),
    ]
