# Generated by Django 4.1.4 on 2023-01-02 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_trainingmain_exercise_alter_training_exercise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="weight",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="training",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.trainingmain"
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.trainingname"
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="reps",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="training",
            name="rir",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="training",
            name="series",
            field=models.CharField(default="Serie nr: ", max_length=10),
        ),
        migrations.AlterField(
            model_name="training",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="trainingmain",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.trainingname"
            ),
        ),
        migrations.AlterField(
            model_name="trainingmain",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
