# Generated by Django 4.1.4 on 2023-01-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_training_weight_alter_training_exercise_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="series",
            field=models.CharField(default="Serie nr: ", max_length=15),
        ),
    ]
