# Generated by Django 4.1.4 on 2023-02-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_rename_training_trainingresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingmain",
            name="reps",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="trainingmain",
            name="rest",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="trainingmain",
            name="rir",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="trainingmain",
            name="tempo",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
