# Generated by Django 4.1.4 on 2023-02-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musclewiki", "0002_alter_exercise_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="muscle",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
