# Generated by Django 4.1.4 on 2023-02-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musclewiki", "0003_alter_muscle_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="exercise",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_name_of_exercise"
            ),
        ),
    ]
