# Generated by Django 4.1.4 on 2023-02-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musclewiki", "0004_exercise_unique_name_of_exercise"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="muscle",
        ),
        migrations.AddField(
            model_name="exercise",
            name="muscle",
            field=models.ManyToManyField(to="musclewiki.muscle"),
        ),
    ]
